baseURL = "https://automate6500.github.io/automate6500-03_02_continuous_deployment_for_github_pages-v2-hugo/"
languageCode = "en-us"
title = "The Amazing API"
description = "The world's most amazing API with AmazingScript"

[permalinks]
  # Use the slug directly to preserve case
  default = "/:slug/"

[params]
  description = "The world's most amazing API with AmazingScript"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
